[project]
name = "sample-python-project"
version = "0.1.0"
description = "Some description"
requires-python = "==3.12.*"
dependencies = [
    "numpy==2.3.4",
    "pandas==2.2.3",
    "black==25.9.0 "
]
